set_property PACKAGE_PIN AA8 [get_ports {GPIO[1]}]
set_property PACKAGE_PIN G14 [get_ports {GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN H18 [get_ports RSTn]
set_property IOSTANDARD LVCMOS33 [get_ports RSTn]
set_property PACKAGE_PIN U12 [get_ports SWCLK]
set_property PACKAGE_PIN U11 [get_ports SWDIO]
set_property IOSTANDARD LVCMOS33 [get_ports SWCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SWDIO]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SWCLK_IBUF]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property PACKAGE_PIN AA9 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN W5 [get_ports {GPIO[3]}]

set_property PACKAGE_PIN K14 [get_ports RXD]
set_property PACKAGE_PIN W8 [get_ports TXD]

set_property IOSTANDARD LVCMOS33 [get_ports RXD]
set_property IOSTANDARD LVCMOS33 [get_ports TXD]

set_property PACKAGE_PIN V8 [get_ports RXD]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN W6 [get_ports {GPIO[2]}]
