set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Led]
set_property IOSTANDARD LVCMOS33 [get_ports Reset_n]
set_property PACKAGE_PIN Y9 [get_ports Clk]
set_property PACKAGE_PIN P20 [get_ports Led]
set_property PACKAGE_PIN H18 [get_ports Reset_n]
