--------------------------------------------------------------
 --     Copyright (c) 2012-2024 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/fpga_class/2025-fpga-anlogic/USB/al_ip/DSP.vhd
 -- Date	:	2025 11 26
 -- TD version	:	5.6.119222
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY DSP IS
PORT (
	p		: OUT STD_LOGIC_VECTOR(56 DOWNTO 0);

	a		: IN STD_LOGIC_VECTOR(40 DOWNTO 0);
	b		: IN STD_LOGIC_VECTOR(15 DOWNTO 0)	);
END DSP;

ARCHITECTURE struct OF DSP IS

	BEGIN
	inst : EG_LOGIC_MULT
		GENERIC MAP (
			INPUT_WIDTH_A	=> 41,
			INPUT_WIDTH_B	=> 16,
			OUTPUT_WIDTH		=> 57,
			INPUTFORMAT		=> "SIGNED",
			INPUTREGA		=> "DISABLE",
			INPUTREGB		=> "DISABLE",
			OUTPUTREG		=> "DISABLE",
			IMPLEMENT		=> "AUTO"
		)
		PORT MAP (
			a		=> a,
			b		=> b,
			p		=> p,
			cea		=> '0',
			ceb		=> '0',
			cepd		=> '0',
			clk		=> '0',
			rstan		=> '0',
			rstbn		=> '0',
			rstpdn	=> '0'
			);

END struct;
