/************************************************************\
 **     Copyright (c) 2012-2024 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/fpga_class/2025-fpga-anlogic/USB/al_ip/DSP.v
 ** Date	:	2025 11 26
 ** TD version	:	5.6.119222
\************************************************************/

`timescale 1ns / 1ps

module DSP ( p, a, b );

	output [56:0] p;

	input  [40:0] a;
	input  [15:0] b;



	EG_LOGIC_MULT #( .INPUT_WIDTH_A(41),
				.INPUT_WIDTH_B(16),
				.OUTPUT_WIDTH(57),
				.INPUTFORMAT("SIGNED"),
				.INPUTREGA("DISABLE"),
				.INPUTREGB("DISABLE"),
				.OUTPUTREG("DISABLE"),
				.IMPLEMENT("AUTO")
			)
			inst(
				.a(a),
				.b(b),
				.p(p),
				.cea(1'b0),
				.ceb(1'b0),
				.cepd(1'b0),
				.clk(1'b0),
				.rstan(1'b0),
				.rstbn(1'b0),
				.rstpdn(1'b0)
			);


endmodule